### PR TITLE
Add spaces between string literals and PRIu64, PRIi64 macros.

### PR DESCRIPTION
**Pull request by falsifian**
This is also at least partly addressed in upstream commit ac52f1061. I needed this change to build the minisat cabal package. Merging upstream changes might also work; I haven't tried that.

### CODE REVIEW

**Comment by falsifian** [comment]
Without the change, I get errors like this:

    minisat/minisat/utils/Options.h:285:33: error:
         error: invalid suffix on literal; C++11 requires a space between literal and identifier [-Wreserved-user
    -defined-literal]
                    fprintf(stderr, "%4"PRIi64, range.begin);
                                        ^
        |                                                                                                        285 |             fprintf(stderr, "%4"PRIi64, range.begin);
        |                                 ^

**Comment by jbransen** [comment]
This is a fork, you are probably are looking for https://github.com/niklasso/minisat/pull/42

**Comment by falsifian** [comment]
Hi @jbransen ,

I did send it to your fork deliberately.  Updating the `minisat` module of your `minisat-bundle` git repo to this commit fixes the `minisat` Cabal package for me.

Maybe you want to incorporate upstream's changes directly instead. I haven't tried that; I only tried this lazy fix.

**Comment by jbransen** [comment]
Right, so could you then send a PR for the `minisat-bundle` repo instead?

**Comment by falsifian** [comment]
Okay, I opened https://github.com/jbransen/minisat-bundle/pull/4 .

But doesn't your `minisat` fork need to include this commit in order for people who clone `minisat-bundle` to be able to fetch it? I'm not very familiar with git submodules; I just saw that git fetched from your fork when I ran whatever command got the submodules properly checked out.

**Pull request closed without merging**
